artifact_location: file:///E:/Folder Kuliah/Semester 7/CAPSTONE PROJECT/Repository/bcs-cow-project/ml/mlflow/999992508245777105
creation_time: 1764056456157
experiment_id: '999992508245777105'
last_update_time: 1764056456157
lifecycle_stage: active
name: BCS-Cattle-Classification
